import { createElement } from "lwc";
import MeetingRooms from "c/meetingRooms";

describe("c-meeting-rooms", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const meetingRooms = createElement("c-meeting-rooms", {
      is: MeetingRooms
    });

    // Act
    document.body.appendChild(meetingRooms);

    const allMeetingRoomComponents =
      meetingRooms.shadowRoot.querySelectorAll("c-meeting-room");
    expect(allMeetingRoomComponents.lenght).toBe(6);
  });
});
